[package]
name = "bdt"
version = "0.1.0"
homepage = "https://github.com/andygrove/bdt"
repository = "https://github.com/andygrove/bdt"
authors = ["Andy Grove <andygrove73@gmail.com>"]
description = "Simple utilities for viewing and converting various Big Data file formats"
license = "Apache-2.0"
edition = "2021"

[dependencies]
